=== abdoulfatah/master_xml/master.dtd
<!--ENTITY-->
<!ENTITY  site1  "Campus Luminy" 		        >
<!ENTITY  site2  "UniversitÃ© d'Aix-Marseille"	>
<!ENTITY  site3  "St Charles" 			        >
<!ENTITY  site4  "St Jerome" 			        >
<!ENTITY  adresseSitePerso      ".perso.luminy.univ-amu.fr/" >
<!ENTITY  http					"http://www."				 >
<!ENTITY  dom.amu				"univ-amu.fr"				 >
<!ENTITY  dom.lif				"lif.univ-mrs.fr"			 >
<!ENTITY  dom.luminy  			"univ-mrs.fr" 				 >
<!ENTITY  dom.dil     			"dil.&dom.luminy;" 			 >
<!ENTITY  obli     				"Obligatoire" 			     >
<!ENTITY  option     				"Optionnel" 			     >
<!ENTITY  cred3     			"3" 			     		 >
<!ENTITY  cred6     			"6" 			     		 >

<!--ELEMENTS-->
<!ELEMENT master					(intervenants,enseignements,parcours,semestres,blocks)>
<!ELEMENT unite    			(nom,identifiant,nombreCredit,professeurs?,resume*,plan?,ref-intervenant*,lieu*)>
<!ELEMENT intervenant				(nom,mail*,siteWeb?)>
<!ELEMENT intervenants        		(intervenant)*>
<!ELEMENT enseignements        		(unite)*>
<!ELEMENT parcours 					(parcour*)>
<!ELEMENT parcour (responsable?,nom,description?,ref-semestre+,debouches*)>
<!ELEMENT semestres					(semestre*)>
<!ELEMENT semestre					(titre,ref-block+)>	
<!ELEMENT blocks 					(block+)>
<!ELEMENT block 					(ref-unite+)>
<!ELEMENT professeurs        		(ref-intervenant+)>
<!ELEMENT responsable        		(ref-intervenant+)>
<!ELEMENT nom 						    (#PCDATA)>
<!ELEMENT plan 						    (#PCDATA)>
<!ELEMENT resume 					    (#PCDATA | p)*>
<!ELEMENT nombreCredit 					(#PCDATA)>
<!ELEMENT identifiant 					(#PCDATA)>
<!ELEMENT mail 						    (#PCDATA)>
<!ELEMENT siteWeb 					    (#PCDATA)>
<!ELEMENT ref-intervenant    			(#PCDATA)>
<!ELEMENT ref-unite   			(#PCDATA)>
<!ELEMENT lieu        				(#PCDATA)>
<!ELEMENT debouches					    (#PCDATA | p )*>
<!ELEMENT description 					(#PCDATA | p)*>
<!ELEMENT ref-semestre   				(#PCDATA)>
<!ELEMENT ref-block						(#PCDATA)>
<!ELEMENT titre        					(#PCDATA)*>
<!--ATTRIBUTS-->
<!ATTLIST unite  id ID  #REQUIRED>
<!ATTLIST intervenant  id ID  #REQUIRED>
<!ATTLIST block  id  ID  #REQUIRED>
<!ATTLIST semestre  id  ID  #REQUIRED>
<!ATTLIST parcour  id  ID  #REQUIRED>
<!ATTLIST ref-intervenant  ref IDREF  #REQUIRED>
<!ATTLIST ref-semestre  ref IDREF  #REQUIRED>
<!ATTLIST ref-unite  ref IDREF  #REQUIRED>
<!ATTLIST ref-block  ref IDREF  #REQUIRED>
<!ATTLIST block  etat  (Obligatoire|Optionnel)  #REQUIRED>

<!--HTML BALISE -->
<!ELEMENT p							(#PCDATA| em | ul | strong | table | p)*  >				
<!ELEMENT strong					(#PCDATA|p)*>				
<!ELEMENT em						(#PCDATA)>
<!ELEMENT ul						(li+ | p)*>
<!ELEMENT li						(#PCDATA|p|ul|table)*>
<!ELEMENT table						(tr+)>
<!ELEMENT tr						(th+|td+)>
<!ELEMENT th						(#PCDATA)>

=== abdoulfatah/master_xml/master.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE master SYSTEM "master.dtd">
<master>
	<intervenants>
		<intervenant id="massat">
			<nom>Jean-Luc MASSAT</nom>
			<mail>jean-luc.massat@&dom.lif;</mail>
		</intervenant>
		<intervenant id="morin">
			<nom>Remi MORIN</nom>
			<mail>remi.morin@&dom.lif;</mail>
		</intervenant>
		<intervenant id="novelli">
			<nom>Noel NOVELLI</nom>
			<mail>noel.novelli@&dom.lif;</mail>
		</intervenant>
		<intervenant id="olive">
			<nom>Frederic OLIVE</nom>
			<mail>frederic.olive@&dom.lif;</mail>
		</intervenant>
		<intervenant id="rene">
			<nom>Lydie RENE CHABAROT</nom>
			<mail>lydie.rene@&dom.lif;</mail>
		</intervenant>
		<intervenant id="sabatier">
			<nom>Claude SABATIER</nom>
			<mail>claude.sabatier@&dom.lif;</mail>
		</intervenant>
		<intervenant id="godard">
			<nom>Emmanuel GODARD</nom>
			<mail>emmanuel.godard@&dom.lif;</mail>
		</intervenant>
		<intervenant id="creignou">
			<nom>Nadia CREIGNOU</nom>
			<mail>nadia.creignou@&dom.lif;</mail>
		</intervenant>
		<intervenant id="bechet">
			<nom>Frederic BECHET</nom>
			<mail>frederic.bechet@&dom.lif;</mail>
		</intervenant>
		<intervenant id="boucelma">
			<nom>Omar BOUCELMA</nom>
			<mail>omar.boucelma@&dom.lif;</mail>
		</intervenant>
		<intervenant id="denis">
			<nom>Francois DENIS</nom>
			<mail>francois.denis@&dom.lif;</mail>
		</intervenant>
		<intervenant id="jamet">
			<nom>Line JAMET</nom>
			<mail>line.jakubiec@&dom.lif;</mail>
		</intervenant>
		<intervenant id="perrot">
			<nom>Kevin PERROT</nom>
			<mail>kevin.perrot@&dom.lif;</mail>
		</intervenant>
		<intervenant id="jegou">
			<nom>Philippe JEGOU</nom>
			<mail>philippe.jegou@&dom.lif;</mail>
		</intervenant>
		<intervenant id="niebert">
			<nom>Peter NIEBERT</nom>
			<mail>peter.niebert@&dom.lif;</mail>
		</intervenant>
		<intervenant id="santocanale">
			<nom>luigi SANTOCANALE</nom>
			<mail>luigi.santocanale@&dom.lif;</mail>
		</intervenant>
		<intervenant id="lugiez">
			<nom>Denis LUGIEZ</nom>
			<mail>denis.lugiez@&dom.lif;</mail>
		</intervenant>
		<intervenant id="contensin">
			<nom>Magali CONTENSIN</nom>
			<mail>magali.contensin@&dom.lif;</mail>
		</intervenant>
	</intervenants>
	<enseignements>
		<unite id="ENSINAU1">
			<nom>Genie Logiciel</nom>
			<identifiant>ENSINAU1</identifiant>
			<nombreCredit>&cred6;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="perrot"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li> Processus logiciel </li>
						<li> Gestion de projet </li>
						<li> Specification et conception (artefact : notation UML) </li>
						<li> Design patterns </li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU2">
			<nom>Complexite</nom>
			<identifiant>ENSINAU2</identifiant>
			<nombreCredit>&cred6;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="olive"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li>Rappels sur les notions d'analyse de la complexite des
							algorithmes et des problemes.
						</li>
						<li>Notion de problemes (decision, recherche, denombrement,
							enumeration, optimisation). Bornes inferieures de complexite.
						</li>
						<li>Classes P et NP. Problemes NP-complets.</li>
						<li>Methodes de resolution des problemes NP-Complets.</li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU3">
			<nom>Reseaux</nom>
			<identifiant>ENSINAU3</identifiant>
			<nombreCredit>&cred6;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="godard"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li>Architecture en couches, standard OSI</li>
						<li>Couche physique</li>
						<li>Couche liaison de Donnees</li>
						<li>Reseau IP</li>
						<li>Algorithmes de routage, routage IP</li>
						<li>Protocole TCP/IP</li>
						<li>Couche Application : HTTP, SMTP, FTP, ...</li>
						<li>Bases des protocoles cryptographiques (terminologie,
							architecture a clef publique).
						</li>
						<li>Introduction a la Securite des reseaux.</li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU4">
			<nom>Programmation fonctionnelle</nom>
			<identifiant>ENSINAU4</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="santocanale"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li>
							Introduction a la programmation fonctionnelle, sur l'exemple
							du langage OCaml Expressions, evaluation, types de base.
							Polymorphisme, ordre superieur. Fonctions recursives, filtrage.
							Les diverses strategies d'evaluation, application a la
							programmation d'un operateur de point fixe.
						</li>
						<li>
							Les types Sommes, types recursifs, polymorphes. Arbres.
							Filtrage.
						</li>
						<li>Semantique operationnelle Liaisons, environnements, clôtures.
							evaluation des fonctions recursives .
						</li>
						<li>
							Aspects imperatifs Exceptions, entrees-sorties, sequencement,
							fichiers, references, tableaux, enregistrements.
						</li>
						<li>
							Implantation du filtrage en OCaml Termes formels,
							substitutions, filtrage.
						</li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU12">
			<nom>BDR : approfondissement</nom>
			<identifiant>ENSINAU12</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="sabatier"></ref-intervenant>
			</professeurs>
			<resume>
				<p> Base de données Rélationnelle </p>
			</resume>
		</unite>
		<unite id="ENSINAU6">
			<nom>Programmation logique</nom>
			<identifiant>ENSINAU6</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="jamet"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li>
							Introduction. Forme generale des regles. Effacement,
							unification, backtracking.
						</li>
						<li> Contrôle de l'execution. </li>
						<li> Listes, arbres et n-uplets. </li>
						<li> Liste representee par difference de listes. Ajout en tete et
							en
							queue, concatenation.
						</li>
						<li>
							Analyseurs syntaxiques. Construction d'un arbre syntaxique.
							Liste des feuilles d'un arbre. Freeze et analyse par feuille.
						</li>
						<li> Regles predefinies.</li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU7">
			<nom>Outils de l'internet</nom>
			<identifiant>ENSINAU7</identifiant>
			<nombreCredit>&cred6;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="contensin"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li> Presentation d'Internet. </li>
						<li> Les langages et les normes sur Internet. </li>
						<li> Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3 </li>
						<li> Les applications web Securite. </li>
						<li> Les nouvelles et futures technologies. </li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU8">
			<nom>Systeme embarque</nom>
			<identifiant>ENSINAU8</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="niebert"></ref-intervenant>
			</professeurs>
			<resume>
				<p> Fabrication des objets connectés </p>
			</resume>
		</unite>

		<unite id="ENSINAU9">
			<nom>Fondamentaux pour l'ingenierie des langues</nom>
			<identifiant>ENSINAU9</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="bechet"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li> Rappel de theorie des langages </li>
						<li> Algorithmes d'analyse </li>
						<li> syntaxique pour grammaires ambiguës </li>
						<li> Transducteurs finis et leur application en TAL </li>
					</ul>
				</p>
			</resume>
		</unite>
		<unite id="ENSINAU10">
			<nom>Modeles a evenements discrets</nom>
			<identifiant>ENSINAU10</identifiant>
			<nombreCredit>&cred6;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="boucelma"></ref-intervenant>
			</professeurs>
			<resume>
				Posseder les notions de base en modelisation et analyse de
				systemes
				dynamiques a evenements discrets et particulierement
				apprehender le
				formalisme reseau de Petri. etudier la conception et
				la specification
				des systemes reactifs a travers l'analyse du modele a evenements
				discrets
				(concurrence, parallelisme, synchronisation).
			</resume>
		</unite>
		<unite id="ENSINAU13">
			<nom>Pratique de la cryptographie</nom>
			<identifiant>ENSINAU13</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<resume>Nous sommes désolé, mais nous n'avons pas encore de résumé.
			</resume>
		</unite>
		<unite id="ENSINBU1">
			<nom>ANGLAIS</nom>
			<identifiant>ENSINBU1</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="jamet"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<ul>
						<li>Apprendre l'anglais</li>
					</ul>
				</p>
			</resume>

		</unite>
		<unite id="ENSINBU2">
			<nom>COMMUNICATION</nom>
			<identifiant>ENSINBU2</identifiant>
			<nombreCredit>&cred3;</nombreCredit>
			<professeurs>
				<ref-intervenant ref="rene"></ref-intervenant>
			</professeurs>
			<resume>
				<p>
					<strong> chapitre 1 : </strong>
					Theories de la communication : 1.1 La theorie
					mathematique de
					l’information (Shannon, Weaver), la cybernetique
					(Wiener)
				</p>
				<p> 1.2 La theorie de Palo Alto ( Bateson, Watzlawick) et la theorie
					de la communication par les processus (Mucchielli)
				</p>
				<p>
					<strong> chapitre 2 : </strong>
					Rôle de l’interculturalite dans le travail en equipe :
					2.1 L’enquete interculturelle de Hofstede pour IBM
					2.2 La gestuelle et le paralangage et la proxemie dans le monde (Hall)
				</p>
				<p>
					<strong> chapitre 3 : </strong>
					Notions de management et de travail collaboratif
					3.1 Le travail collaboratif vs le travail cooperatif
					3.2 La notion de groupes
